### ISSUE TITLE
Kext fails to load, missing _memcpy_chk in kernel

### ISSUE THREAD

**Issue by abbc01** [rgov/Thunderbolt3Unblocker#12]
Thank you for the project.
I have some difficulties in building the project, 

i have done (csrutil enable --without kext.), and when i run the project, fail comes up.
<img width="778" alt="screen shot 2018-04-05 at 7 44 57 pm" src="https://user-images.githubusercontent.com/38102975/38364261-6fa5bab2-390a-11e8-9205-053002d51efe.png">

and try to put this in, but i dunno am i doing wrong,
git submodule update --init --recursive
brew install cmake

<img width="839" alt="screen shot 2018-04-05 at 7 52 35 pm" src="https://user-images.githubusercontent.com/38102975/38364371-ef032182-390a-11e8-8148-a0a3477ea6a6.png">

i am very new to xcode and programming, so if i haven't done sth very minor, please tell me step by step, thank you very much.

**Comment by rgov** [comment]
Hi @abbc01, I'm afraid your method is not correct. I've published a pre-compiled version for you, please let me know if you have further problems.

https://github.com/rgov/Thunderbolt3Unblocker/releases

**Comment by abbc01** [comment]
Dear @rgov 

Thank for you reply, but it still not working, i have done csrutil enable --without kext && reboot again,  and unzip and place the kext into the extensions,

<img width="776" alt="screen shot 2018-04-05 at 11 38 02 pm" src="https://user-images.githubusercontent.com/38102975/38376109-6f352552-392a-11e8-8245-84e647ab55fa.png">

and i run after i run
(sudo sh -c 'chown -R root:wheel /Library/Extensions/Thunderbolt3Unblocker.kext && \
kextcache -i / && \
kextload -b es.govost.ryan.Thunderbolt3Unblocker')

<img width="1073" alt="screen shot 2018-04-05 at 11 39 16 pm" src="https://user-images.githubusercontent.com/38102975/38376210-b01481b2-392a-11e8-86d0-a910c2c53d43.png">

after reboot and unplug several time, it's still not working...

<img width="792" alt="screen shot 2018-04-05 at 11 40 57 pm" src="https://user-images.githubusercontent.com/38102975/38376270-d1d814ee-392a-11e8-95a0-77f5b3d1aa0a.png">

**Comment by abbc01** [comment]
and i also go into the content and run Thunderbolt3Unblocker

<img width="1514" alt="screen shot 2018-04-05 at 11 59 07 pm" src="https://user-images.githubusercontent.com/38102975/38377369-5e7bef0e-392d-11e8-9afe-420b3d4c6895.png">

**Comment by rgov** [comment]
Thanks @abbc01. Could you please tell me the version of macOS you are using? Also please note that you cannot "run" kernel extensions like you showed, they are not like apps.

**Comment by abbc01** [comment]
<img width="345" alt="screen shot 2018-04-06 at 12 08 51 am" src="https://user-images.githubusercontent.com/38102975/38377920-c6aae020-392e-11e8-9851-7ee0328e3471.png">

10.12.6 (16G1212)

thank you

**Comment by abbc01** [comment]
It works!! thank you so much @rgov

**Comment by rgov** [comment]
Thanks for testing. Enjoy your device!

**Comment by rgov** [comment]
macOS Sierra support is now available in release v0.0.2 and newer. https://github.com/rgov/Thunderbolt3Unblocker/releases
